Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.56.101"
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
	vb.memory = 1600
	vb.cpus = 2
  end
end
